### PR TITLE
Excluded Gulpfile and db/mongo

### PR DESCRIPTION
**Pull request by ekapaul**
Brought up coverage

### CODE REVIEW

**Comment by ssabpisa** [comment]
Or maybe I should make the test setup mongo db somehow?

**Comment by abalmos** [comment]
We should probably write unit tests that run after oada-compliance for things like db/mongo and other bits that are hard / don't make sense as compliance tests.

**Comment by awlayton** [comment]
So... seems OK to me.

**Comment by abalmos** [comment]
@ssabpisa Can you not exclude db/mongo so that we don't forget to write those tests ?

**Pull request merged**
